app/dashboard/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired, Email, EqualTo


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    post_type = SelectField('Post Type:', choices=[('2', 'Blog'), ('1', 'Project')], validators=[DataRequired()])
    published = BooleanField('Publish?')
    submit = SubmitField('Save Post')


class UpdateUserForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Update')

app/dashboard/__init__.py
from flask import Blueprint

bp = Blueprint('dashboard', __name__)

from app.dashboard import routes

app/dashboard/routes.py
import os
import secrets
import json
from app import db
from app.dashboard import bp
from app.dashboard.forms import UpdateUserForm, PostForm
from app.models import User, Post
from datetime import datetime
from flask import current_app, render_template, redirect, url_for, flash, request
from flask_login import current_user, login_required
from PIL import Image
from slugify import slugify


@bp.route('/dashboard')
@login_required
def dashboard():
    user = User.query.filter_by(username=current_user.username).first_or_404()
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(page=page, per_page=10)
    return render_template('dashboard/dashboard.html', user=user, posts=posts)


@bp.route('/update_user', methods=['GET', 'POST'])
@login_required
def update_user():
    form = UpdateUserForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data.lower()
        hashed_password = current_user.set_password(form.password.data)
        current_user.password = hashed_password
        db.session.commit()
        flash('Your credentials have been updated.')
        return redirect(url_for('dashboard.dashboard'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('dashboard/update_user.html', title='Update Credentials', form=form)


@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()


@bp.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user, content_type=form.post_type.data, published=form.published.data, slug=slugify(form.title.data))
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created.')
        return redirect(url_for('dashboard.dashboard'))
    return render_template('dashboard/create_post.html', title='New Post', form=form, legend='New Post')


@bp.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.content_type = form.post_type.data
        post.published = form.published.data
        post.slug = slugify(form.title.data)
        db.session.commit()
        flash('Your post has been updated!')
        return redirect(url_for('dashboard.dashboard'))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
        form.post_type.data = post.content_type
        form.published.data = post.published
    return render_template('dashboard/create_post.html', title='Update Post', form=form, legend='Edit Post')


@bp.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!')
    return redirect(url_for('dashboard.dashboard'))


@bp.route('/upload', methods=['GET', 'POST'])
def upload():
    if request.method == 'POST':
        file = request.files['file']
        extension = os.path.splitext(file.filename)[1]
        f_name = secrets.token_hex(8) + extension
        with Image.open(file) as img:
            width, height = img.size
            if width > 700 or height > 500:
                maxsize = (700, 500)
                img.thumbnail(maxsize, Image.ANTIALIAS)
            img.save(os.path.join(current_app.root_path, 'static/media/img', f_name))
        return json.dumps({'filename': f_name})

app/templates/dashboard/create_post.html
{% extends "dashboard/dashboard_base.html" %}

{% block script %}
<script src="{{ url_for('static', filename='js/jquery-3.3.1.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.ui.widget.js') }}"></script>

<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.fileupload.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.fileupload-process.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.fileupload-ui.js') }}"></script>

<script type="text/javascript" src="{{ url_for('static', filename='js/dashboard.js') }}"></script>
<script>

</script>
{% endblock script %}

{% block content %}
<h1>New Post/Edit Post</h1>
<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="fieldset-post">
            <legend>{{ legend }}</legend>
            <div>
                {{ form.title.label(class="post-input-label") }}
                {% if form.title.errors %}
                    {{ form.title }}
                    <div>
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="post-input post-input-title") }}
                {% endif %}
            </div>
            <div>
                {{ form.content.label(class="post-input-label") }}
                {% if form.content.errors %}
                    {{ form.content }}
                    <div>
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="post-input post-input-textarea", id="post-input-textarea") }}
                {% endif %}
            </div>
            <div id="add-project-structure" class="button button-info">
                <small>Project</small>
            </div>
            <div id="add-blogpost-structure" class="button button-info">
                <small>Blog</small>
            </div>
            <div>
                {{ form.post_type.label(class="post-input-label") }}
                {% if form.post_type.errors %}
                    {{ form.post_type }}
                    <div>
                        {% for error in form.post_type.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.post_type }}
                {% endif %}
            </div>
            <p>{{ form.published() }} {{ form.published.label }}</p>
        </fieldset>
        </div>
        <div>
            Upload Images: <input class="button-upload" type="file" id="fileupload" name="file" multiple>
            <div>
              <img id="imgUpload" style="width: 140px; height: 140px;" class="img-thumbnail"><input type="text" name="filePath" id="filePath"></input>
            </div>
        </div>
        <div>
            {{ form.submit(class="button button-success") }}
        </div>
    </form>
    <form enctype="multipart/form-data">

    </form>
</div>
{% endblock content %}

app/templates/dashboard/dashboard.html
{% extends 'dashboard/dashboard_base.html' %}

{% block content %}
    <h1>Dashboard</h1>
    <section>
        <a class="button button-success" href="{{ url_for('dashboard.new_post') }}">New Post</a>
        <h2>Posts Overview</h2>
        <table class="posts-overview">
            <tr>
                <td><strong>Title</strong></td>
                <td><strong>Date Posted</strong></td>
                <td><strong>Type</strong></td>
                <td><strong>Published?</strong></td>
                <td><strong>Edit</strong></td>
                <td><strong>Delete</strong></td>
            </tr>
            {% for post in posts.items %}
            <tr>
                <!-- The url_for link building throws up an error here and says it is missing
                    the "slug" parameter. The same route building works in other templates.
                    Went around this by building the link this way: -->
                <td><a href="post/{{ post.id }}/{{ post.slug }}">{{ post.title }}</a></td>
                <td>{{ post.timestamp.strftime('%Y-%m-%d') }}</td>
                <td>{{ post.content_type }}</td>
                <td>{{ post.published }}</td>
                <td><a class="button button-info" href="{{ url_for('dashboard.edit_post', post_id=post.id) }}">Edit</a></td>
                <td><a class="button button-danger" href="#open-modal">Delete</a>
                    <!-- Modal for Delete Post -->
                    <div id="open-modal" class="modal-dialog">
                        <div>
                            <a href="#close" title="Close" class="modal-close">X</a>
                            <h2>Delete Post?</h2>
                            <p>
                                This post will be deleted: {{ post.title }}
                            </p>
                            <p>
                                Continue?
                            </p>
                            <p>
                                <a href="#close" class="button button-info">Cancel</a>
                                <form action="{{ url_for('dashboard.delete_post', post_id=post.id )}}" method="POST"><input class="button button-danger" type="submit" value="Delete"></form>
                            </p>
                        </div>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </table>
        <p>
            {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
              {% if page_num %}
                {% if posts.page == page_num %}
                  <a class="button button-success" href="{{ url_for('dashboard.dashboard', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                  <a class="button button-info" href="{{ url_for('dashboard.dashboard', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
              {% else %}
                ...
              {% endif %}
            {% endfor %}
        </p>
    </section>

{% endblock content %}

app/templates/dashboard/dashboard_base.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ current_user.username }}'s Dashboard on stefanpfeuffer.com</title>

    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='media/favicon.ico') }}" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='dashboard.css') }}">

    <script type=text/javascript>
        $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    </script>

    {% block script %}
    {% endblock script %}

</head>
<body>
    <header>
        <nav class="navbar-container">
            <div>
            User: {{ current_user.username }} |
            {% if current_user.last_seen %}
                Last seen on: {{ current_user.last_seen.strftime('%Y-%m-%d at %H:%M') }} UTC
            {% endif %}
            </div>
            <ul class="navbar">
                <li><a href="{{ url_for('dashboard.dashboard') }}">Home</a></li>
                <li><a href="{{ url_for('dashboard.update_user') }}">Change Credentials</a></li>
                <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
            </ul>
        </nav>
    </header>
    <div class="content-container">
        <main class="content">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <p class="flash-message"><strong>{{ message }}</strong></p>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}
            {% endblock content %}
        </main>
    </div>
</body>
</html>

app/templates/dashboard/update_user.html
{% extends 'dashboard/dashboard_base.html' %}

{% block content %}
    <h1>Update Credentials</h1>
    <form action="" method="POST" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}
            {% for error in form.username.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=32) }}
            {% for error in form.email.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}
            {% for error in form.password.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.confirm_password.label }}<br>
            {{ form.confirm_password(size=32) }}
            {% for error in form.password.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock content %}